//! Core types, parameters, and telemetry for Successive Convexification (SCvx).
//!
//! Grounded in:
//! - **Mao, Y., Szmuk, M., & Açıkmeşe, B. (2016)**.  
//!   *Successive Convexification of Non-Convex Optimal Control Problems and Its Convergence Properties.*  
//!   arXiv:1608.05133 (Section II, Algorithm 1, & Section IV Table I).
//! - **Malyuta, D., Reynolds, T. P., Szmuk, M., et al. (2022)**.  
//!   *Convex Optimization for Trajectory Generation: A Tutorial on Generating Dynamically Feasible Trajectories Reliably and Efficiently.*  
//!   IEEE Control Systems Magazine, 42(5), 40–113 (arXiv:2106.09125, Table 1 & Algorithm 2).

/// User-selected algorithmic parameters for Successive Convexification (Algorithm 1 in Mao 2016 / Table 1 in Malyuta 2021).
#[derive(Debug, Clone, PartialEq)]
pub struct ScvxOptions {
    /// Number of temporal discretization nodes $N$. Default: 30.
    pub n_nodes: usize,
    /// Initial trust region radius $\Delta_0$. Default: 2.0.
    pub initial_trust_region: f64,
    /// Minimum lower bound on trust region radius $\Delta_l$. Default: 1e-4.
    pub min_trust_region: f64,
    /// Trust region expansion/contraction factor $\alpha > 1$. Default: 2.0.
    pub alpha: f64,
    /// Virtual control penalty weight $\lambda > 0$. Default: 1000.0.
    pub virtual_control_weight: f64,
    /// Trust region rejection threshold $\rho_0$. Default: 0.0.
    pub rho_0: f64,
    /// Trust region contraction threshold $\rho_1$. Default: 0.25.
    pub rho_1: f64,
    /// Trust region expansion threshold $\rho_2$. Default: 0.9.
    pub rho_2: f64,
    /// Maximum outer-loop SCvx iterations. Default: 30.
    pub max_iterations: usize,
    /// Virtual control feasibility convergence tolerance $\|\boldsymbol{\nu}\|_1 \le \epsilon_{\nu}$. Default: 1e-5.
    pub tol_virtual_control: f64,
    /// State increment convergence tolerance $\|\Delta \mathbf{x}\| \le \epsilon_x$. Default: 1e-4.
    pub tol_state_increment: f64,
}

impl Default for ScvxOptions {
    fn default() -> Self {
        Self {
            n_nodes: 30,
            initial_trust_region: 2.0,
            min_trust_region: 1e-4,
            alpha: 2.0,
            virtual_control_weight: 1000.0,
            rho_0: 0.0,
            rho_1: 0.25,
            rho_2: 0.9,
            max_iterations: 30,
            tol_virtual_control: 1e-5,
            tol_state_increment: 1e-4,
        }
    }
}

/// Telemetry recorded at each outer-loop SCvx succession (Algorithm 1 Steps 2–3).
#[derive(Debug, Clone, PartialEq)]
pub struct ScvxIterationReport {
    /// Succession index $k$ (1-indexed).
    pub iteration: usize,
    /// True non-linear cost $J(\mathbf{x}_k, \mathbf{u}_k)$.
    pub cost_actual: f64,
    /// Predicted linear cost $L(\mathbf{d}_k, \mathbf{w}_k)$.
    pub cost_predicted: f64,
    /// Actual cost change $\Delta J_k = J(\mathbf{x}_k) - J(\mathbf{x}_k + \mathbf{d}_k)$.
    pub delta_cost_actual: f64,
    /// Linearized predicted cost change $\Delta L_k = J(\mathbf{x}_k) - L(\mathbf{d}_k)$.
    pub delta_cost_predicted: f64,
    /// Quality ratio $r_k = \Delta J_k / \Delta L_k$.
    pub ratio_r: f64,
    /// Trust region radius $\Delta_k$ used for this succession.
    pub trust_region_radius: f64,
    /// Maximum $L_1$ norm of virtual control defects $\|\boldsymbol{\nu}\|_1$.
    pub virtual_control_norm: f64,
    /// Maximum norm of state increment $\|\mathbf{d}_k\|$.
    pub state_increment_norm: f64,
    /// Whether the trial step was accepted ($r_k \ge \rho_0$).
    pub step_accepted: bool,
}

/// State at a single trajectory node.
#[derive(Debug, Clone, PartialEq)]
pub struct TrajectoryNode {
    pub time: f64,
    pub state: Vec<f64>,
    pub control: Vec<f64>,
    pub virtual_control: Vec<f64>,
}

/// Complete solution generated by the Successive Convexification engine.
#[derive(Debug, Clone, PartialEq)]
pub struct ScvxSolution {
    /// Whether the optimizer converged to physical feasibility ($\|\boldsymbol{\nu}\|_1 \le \epsilon$).
    pub converged: bool,
    /// Total outer-loop iterations.
    pub total_iterations: usize,
    /// Number of accepted successions.
    pub accepted_successions: usize,
    /// Final objective cost (fuel / propellant consumption).
    pub final_cost: f64,
    /// Final virtual control residual ($\|\boldsymbol{\nu}\|_1 \approx 0$).
    pub final_virtual_control_residual: f64,
    /// Discretized trajectory node states and controls.
    pub nodes: Vec<TrajectoryNode>,
    /// Step-by-step iteration logs for convergence auditing.
    pub iteration_history: Vec<ScvxIterationReport>,
}
